name: AiRi
description: A Flutter AiRi.

version: 0.0.2

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_screenutil: ^1.0.2
  provider: ^4.0.4
  transparent_image: ^1.0.0
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.0.0
  webview_flutter: ^0.3.19+8
  permission_handler: ^4.3.0
  flutter_splash_screen: ^0.1.0
  oktoast: ^2.3.1+1
  dio: ^3.0.9
  tuple: ^1.0.3
  underline_indicator: ^0.0.2
  pull_to_refresh: ^1.5.8
  easy_localization: ^2.0.2
  shared_preferences: ^0.5.6+3
  url_launcher: ^5.4.2
  sqflite: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    # LOGO
    - assets/images/logo.png
    # 导航栏
    - assets/images/nav/nav_back.png
    # tab bar
    - assets/images/tabbar/zhuye_ON.png
    - assets/images/tabbar/zhuye_off.png
    - assets/images/tabbar/fenlei_ON.png
    - assets/images/tabbar/fenlei_off.png
    - assets/images/tabbar/diangdan_ON.png
    - assets/images/tabbar/dingdan_off.png
    - assets/images/tabbar/guanli_ON.png
    - assets/images/tabbar/guanli_off.png

    # 首页
    - assets/images/home/gouwuche.png
    - assets/images/home/sousuo.png
    - assets/images/home/gengduofenlei.png
    - assets/images/home/jiazaizhong.png
    - assets/images/home/fenxiang.png
    - assets/images/home/lianxi.png
    - assets/images/home/shop.png

    # 详情页
    - assets/images/detail/up.png
    - assets/images/detail/dowm.png

    # 供应商页面
    - assets/images/supplier/fenxiang.png
    - assets/images/supplier/beijing.png
    - assets/images/supplier/weizi.png
    - assets/images/supplier/lianxiren.png
    - assets/images/supplier/shijian.png

    # 购物车
    - assets/images/shopping_cart/bottom_check.png
    - assets/images/shopping_cart/check_un.png
    - assets/images/shopping_cart/check.png
    - assets/images/shopping_cart/down.png
    - assets/images/shopping_cart/down1.png
    - assets/images/shopping_cart/icon-sj-26.png
    - assets/images/shopping_cart/up.png
    - assets/images/shopping_cart/jiazaizhong.png
    - assets/images/shopping_cart/empty.png

    # 订单
    - assets/images/order/empty.png
    - assets/images/order/jiazaizhong.png
    - assets/images/order/querendingdan.png

    # 支付页
    - assets/images/pay/check.png
    - assets/images/pay/uncheck.png

    # 确认订单页面
    - assets/images/confirm_order/edit.png
    - assets/images/confirm_order/dingdanchenggong.png

    # 登录页面
    - assets/images/login/phone.png
    - assets/images/login/password.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
